chatgpt:
  api_key : ""

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gccproject?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: dkfvldpa1!

  security:
    user:
      password: asdf